//常量库
class Constants {
  readonly CONTEXT: string = 'Context' //上下文
  readonly TOP_AREA: string = 'Top_Area'
  readonly BOTTOM_AREA: string = 'Bottom_Area'
  readonly TRACKING_STORY: string = 'Tracking_story'
  readonly TRACK_LIST: string = 'track_list'
  readonly HISTORY_KEY: string = 'History_story'
  readonly UPDATE_RECORD_LIST: string = 'update_record_list'
}

export const constants = new Constants()