//常量库
class Constants {
  readonly CONTEXT: string = 'Context' //上下文
  readonly TOP_AREA: string = 'Top_Area'
  readonly BOTTOM_AREA: string = 'Bottom_Area'
  readonly TRACKING_STORY: string = 'Tracking_story'
  readonly TRACK_LIST: string = 'Track_list'
  readonly HISTORY_KEY: string = 'History_story'
  readonly UPDATE_RECORD_LIST: string = 'Update_record_list'
  readonly THEME_KEY: string = 'Theme_key'
  readonly IS_DARK: string = 'Is_dark'
}

export const constants = new Constants()